### return All users
GET http://localhost:8080/academics/api/users
Accept: application/json

### return Sensor Id
GET http://localhost:8080/academics/api/sensors/1
Accept: application/json

### All Orders
GET http://localhost:8080/academics/api/orders
Accept: application/json

###Order Details
GET http://localhost:8080/academics/api/orders/1
Accept: application/json

### Order Create
POST http://localhost:8080/academics/api/orders
Content-Type: application/json

{

  "customerId": 3,
  "manufacturerId": 1,
  "logisticOperatorId" : 5,
  "orderDate": "2024-02-12",
  "deliveryDate": null,
  "estimatedDeliveryTime": "1 week",
  "packageLocation": "Coimbra",
  "city": "Coimbra",
  "postalCode": "3000-000",
  "country": "Portugal",
  "address": "Rua do Brasil",
  "paymentMethod": "Credit Card",
  "status": "Pending",
  "count" : 25.98,
  "orderItems": [
    {
      "productPackageId": 2,
      "quantity": 2,
      "subPrice": 12.99
    },
    {
      "productPackageId": 4,
      "quantity": 1,
      "subPrice": 12.99
    }
    ]
}

###OrderItems by Order Id
GET http://localhost:8080/academics/api/orders/3/items
Accept: application/json

### Order Sensors Id
GET http://localhost:8080/academics/api/orders/1/sensors
Accept: application/json

### Order Update by Id
PUT http://localhost:8080/academics/api/orders/1
Content-Type: application/json

{
  "deliveryDate": "2024-02-11",
  "estimatedDeliveryTime": "2024-02-15",
  "packageLocation": "Coimbra",
  "status": "Sending"
}

### Products All
GET http://localhost:8080/academics/api/products/
Accept: application/json


### Product create
POST http://localhost:8080/academics/api/products/
Content-Type: application/json

{
  "name": "Product 2",
  "brand": "Some other Brand",
  "description": "another best product ever",
  "totalQuantity": 180,
  "manufacturerId": 1
}

### Product by Id
GET http://localhost:8080/academics/api/products/3
Accept: application/json

### Product Delete by Id
DELETE http://localhost:8080/academics/api/products/3

### Product Update by Id
PUT http://localhost:8080/academics/api/products/3
Content-Type: application/json

{
  "name": "Product updated",
  "brand": "Some Updated Brand",
  "description": "another best product ever",
  "totalQuantity": 180,
  "manufacturerUsername": "joao"
}


### Package All
GET http://localhost:8080/academics/api/packages/
Accept: application/json

### Package create
POST http://localhost:8080/academics/api/packages/
Content-Type: application/json

{
  "name": "Package 1",
  "packageType": 3,
  "material": "Plastic",
  "sensorsTypes": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}

### Package by Id
GET http://localhost:8080/academics/api/packages/5
Accept: application/json

### Package Update by Id
PUT http://localhost:8080/academics/api/packages/5
Content-Type: application/json

{
  "name": "Package 1",
  "packageType": 3,
  "material": "Plastic",
  "sensorsTypes": [
    {
      "id": 1
    }
  ]
}

### Package Delete by Id
DELETE http://localhost:8080/academics/api/packages/6

### ProductPackage All
GET http://localhost:8080/academics/api/productPackages/

### ProductPackage by Id
GET http://localhost:8080/academics/api/productPackages/5
Accept: application/json

### ProductPackage create
POST http://localhost:8080/academics/api/productPackages/
Content-Type: application/json

{
  "productCode": 1,
  "packageCode": 3,
  "price": 12.99,
  "quantityProductsInPackage": 10,
  "image": "Not Available"
}

### ProductPackage Update by Id
PUT http://localhost:8080/academics/api/productPackages/5
Content-Type: application/json

{
  "price": 15.99,
  "quantityProductsInPackage": 24,
  "image": "Not Available"
}

### ProductPackage Delete by Id
DELETE http://localhost:8080/academics/api/productPackages/5


### Manufacturer Id
GET http://localhost:8080/academics/api/manufacturers/1
Accept: application/json

### Manufacturer Products
GET http://localhost:8080/academics/api/manufacturers/1/products
Accept: application/json

### Manufacturer Orders
GET http://localhost:8080/academics/api/manufacturers/1/orders

### Manufacturer Create
POST http://localhost:8080/academics/api/manufacturers/
Content-Type: application/json

{
    "username": "JoeMax",
    "password": "123",
    "name": "Joe",
    "email": "joemax@gmail.com",
  "role": 1
}

### Manufacturer Update by Id
PUT http://localhost:8080/academics/api/manufacturers/5
Content-Type: application/json

{
    "username": "JoeMax",
    "password": "123",
    "name": "Joe",
    "email": "joeUpdates@gmail.com",
    "role": 1
}

### Manufacturer Delete by Id
DELETE http://localhost:8080/academics/api/manufacturers/5


### LogisticOperator Id
GET http://localhost:8080/academics/api/logistic-operators/5
Accept: application/json

### LogisticOperator Orders
GET http://localhost:8080/academics/api/logistic-operators/5/orders
Accept: application/json

### LogisticOperator Create
POST http://localhost:8080/academics/api/logistic-operators/
Content-Type: application/json

{
  "username": "LogisticMax",
  "password": "123",
  "name": "Logistic",
  "email": "maxi@gmail.com",
  "role": 3
}

### LogisticOperator Delete by Id
DELETE http://localhost:8080/academics/api/logistic-operators/5

### LogisticOperator Update by Id
PUT http://localhost:8080/academics/api/logistic-operators/5
Content-Type: application/json

{
  "username": "LogisticMaxUpdated",
  "password": "123",
  "name": "Logistic",
  "email": "newemail@gmail.com",
  "role": 3
}

### Customer Id
GET http://localhost:8080/academics/api/customers/5
Accept: application/json

### Customer Orders
GET http://localhost:8080/academics/api/customers/2/orders
Accept: application/json

### Customer Cart
GET http://localhost:8080/academics/api/customers/3/cart
Accept: application/json

### Customer Create
POST http://localhost:8080/academics/api/customers/
Content-Type: application/json

{
  "username": "CustomerMax",
  "password": "123",
  "name": "Customer",
  "email": "hola@gmail.com",
  "role": 2
}

### Customer Update by Id
PUT http://localhost:8080/academics/api/customers/5
Content-Type: application/json

{
  "username": "CustomerNew",
  "password": "123",
  "name": "Customer",
  "email": "updatedmeail@gmail.com",
  "role": 2
}

### Customer Delete by Id
DELETE http://localhost:8080/academics/api/customers/6

### CartItem Create
POST http://localhost:8080/academics/api/carts/2/items/
Content-Type: application/json

{
  "productPackageId": 2,
  "quantity": 1,
  "subPrice": 4.99
}

### CartItem Remove by Id
DELETE http://localhost:8080/academics/api/carts/2/items/5

### CartItem Update by Id
PATCH http://localhost:8080/academics/api/carts/2/items/4
Content-Type: application/json

{
  "quantity": 3,
  "subPrice": 14.97
}

### CartItem Clean
PUT http://localhost:8080/academics/api/carts/2/clean
